####################################################
#
# Welcome to Applin Doxy Jekyll Template
#
# Product Link : https://themeix.com/product/doxy-documentation-website-jekyll-template/
# Version : v2.1.0
#
####################################################

# Site settings
title: "UPADED"
email: ""
description: "Universidad PÃºblica, Abierta y a Distancia del Estado de Durango"
keywords: "universidad, publica, abierta, distancia, durango"
baseurl: "/upaded" # the subpath of your site, e.g. /blog
url: "https://trazzos.github.io/upaded/" # the base hostname & protocol for your site, e.g. http://example.com
cover_image: "https://themeix.com/wp-content/uploads/dooxy-responsive-html-template-preview.png"
## Theme Options
animated_header: ""  #true 
twitter_username: jekyllrb
github_username:  jekyll




# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed


# Tag Options
tag_page_layout: tag_page
tag_page_dir: tag

permalink: /:title/ 
 
collections:
  team_members:
    output: true
    permalink: /team_members/:path/
  testimonials:
    output: true
    permalink: /testimonials/:path/
  docs:
    output: true
    permalink: /docs/:path/
  cecv:
    output: true
    permalink: /i/cecv/:path/
  eevp:
    output: true
    permalink: /i/eevp/:path/
  hdev:
    output: true
    permalink: /i/hdev/:path/



# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/  d
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/